// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nepaajqledwgtysuqmti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lcGFhanFsZWR3Z3R5c3VxbXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzM0NzYsImV4cCI6MjA2NDQ0OTQ3Nn0.VOjzesHATM-AKkM_uQzMgU6wI4GGF54F_aFGcW_s9Sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);